# syntax=docker.io/docker/dockerfile:1.7-labs

FROM lukemathwalker/cargo-chef:latest-rust-1.96-trixie AS chef
WORKDIR /app
COPY .github/scripts/install_llvm_ubuntu.sh /tmp/install_llvm.sh
RUN /tmp/install_llvm.sh && rm /tmp/install_llvm.sh && \
    apt-get install -y --no-install-recommends libclang-dev m4 pkg-config

FROM chef AS planner
COPY --exclude=.git --exclude=dist . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
ARG BUILD_PROFILE=release
ENV BUILD_PROFILE=$BUILD_PROFILE
ARG RUSTFLAGS=""
ENV RUSTFLAGS=$RUSTFLAGS
ARG FEATURES=""
ENV FEATURES=$FEATURES
ARG VERGEN_GIT_SHA
ARG VERGEN_GIT_DESCRIBE
ARG VERGEN_GIT_DIRTY=false
ENV VERGEN_GIT_SHA=$VERGEN_GIT_SHA
ENV VERGEN_GIT_DESCRIBE=$VERGEN_GIT_DESCRIBE
ENV VERGEN_GIT_DIRTY=$VERGEN_GIT_DIRTY
RUN --mount=type=cache,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,target=/usr/local/cargo/git,sharing=locked \
    cargo chef cook --profile "$BUILD_PROFILE" --features "$FEATURES" --recipe-path recipe.json
COPY --exclude=.git --exclude=dist . .
RUN --mount=type=cache,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,target=/usr/local/cargo/git,sharing=locked \
    cargo build --profile "$BUILD_PROFILE" --features "$FEATURES" --locked --bin reth && \
    cp "/app/target/$BUILD_PROFILE/reth" /app/reth

FROM ubuntu:24.04 AS runtime
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/reth /usr/local/bin/reth
EXPOSE 30303 30303/udp 9001 8545 8546
ENTRYPOINT ["/usr/local/bin/reth"]
