reload_interval = "2s"
server_address = "0.0.0.0:8080"
chain_name = "tempo-revm-vs-evm2"

[[clients]]
url = "http://tempo-revm:8545"
name = "tempo-revm"
kind = "rpc"

[[clients]]
url = "http://tempo-evm2:8545"
name = "tempo-evm2"
kind = "rpc"
